# For development env
spring:
  data:
    cassandra:
      local-datacenter: "Moon"

project:
  cassandra:
    keyspace:
      name: 'Messenger'
      replication-factor: 2
      durable-writes: true
    dc: "Moon"
    rack: "West"
    seeds:
      - '127.0.0.1:9042'
    schema:
      init: true
      scripts: 'cassandra-scripts/schema.cql'
    data:
      init: true
      scripts: 'cassandra-scripts/data.cql'


