#For deployment
spring:
  profiles:
    active: dev

  jackson:
    serialization:
      write-dates-as-timestamps: false


#project:
#  cassandra:
#    keyspace:
#      name: 'Messenger'
#      replication-factor: 2
#      durable-writes: true
#    dc: "Moon"
#    rack: "West"
#    seeds:
#      - '127.0.0.1:9042'
#    schema:
#      init: false
#      scripts: 'classpath:cassandra-scripts/schema.cql'
#    data:
#      init: false
#      scripts: 'classpath:cassandra-scripts/data.cql'
