# For development env
spring:
  data:
    cassandra:
      local-datacenter: "Moon"

project:
  customEpochMilli: 1640995200000
  bucketing:
    bucketSize: 7776000000 # 3 months (3 * 30 * 24 * 60 * 60 * 1000) in ms
  cassandra:
    keyspace:
      name: 'Messenger'
      replication-factor: 2
      durable-writes: true
    dc: "Moon"
    rack: "West"
    seeds:
      - '127.0.0.1:9042'
    schema:
      init: true
      scripts: 'cassandra-scripts/schema.cql'
    data:
      init: true
      scripts: 'cassandra-scripts/data.cql'


