management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://dev-20836463.okta.com/oauth2/default'

project:
  customEpochMilli: 1640995200000
  bucketing:
    bucketSize: 7776000000 # 3 months (3 * 30 * 24 * 60 * 60 * 1000) in ms
  kafka:
    bootstrap-servers: '127.0.0.1:9092,127.0.0.1:9093'
    value-deserializer: 'io.confluent.kafka.serializers.KafkaAvroDeserializer'
    value-serializer: 'io.confluent.kafka.serializers.KafkaAvroSerializer'
    key-deserializer: 'io.confluent.kafka.serializers.KafkaAvroDeserializer'
    key-serializer: 'io.confluent.kafka.serializers.KafkaAvroSerializer'
    topics:
      thread-events: "thread.events"
    group-id: "instance01"
  cassandra:
    keyspace:
      name: 'Messenger'
      replication-factor: 2
      durable-writes: true
    dc: "Moon"
    rack: "West"
    clusterName: "MilkyWay"
    seeds:
      - '127.0.0.1:9042'
    schema:
      init: true
      scripts: 'cassandra-scripts/schema.cql'
    data:
      init: true
      scripts: 'cassandra-scripts/data.cql'
    driver-config: 'classpath:application.conf'
  idp:
    okta:
      orgUrl: 'https://dev-20836463.okta.com'
      apiKey: ${OKTA_API_KEY}

  cors:
    enabled: true
    allowed-headers:
      - 'Authorization'
      - 'Content-Type'
      - 'Accept'
      - 'Origin'
    allowed-methods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'DELETE'
      - 'OPTIONS'
      - 'PATCH'
    allowed-origins:
      - "http://localhost:4200"


logging:
  level:
    com:
      akmal:
        messengerspringbackend: TRACE
    org:
      springframework:
        security: DEBUG
        web:
          socket: TRACE
